export type ServiceCategory = 'web' | 'eshop' | 'seo' | 'texty' | 'social' | 'cold-email' | 'email-marketing';

export interface Client {
  name: string;
  website: string;
  categories: ServiceCategory[];
  logoUrl?: string; // will be fetched via Clearbit/Google
}

// Excluded: SLAVBIZ, Ato online, ARMO-SK
// Excluded: individuals without company websites
export const clients: Client[] = [
  { name: "Andrej Siváček Audio Tuning", website: "https://audiotuning.sk", categories: ["eshop"] },
  { name: "SK studio", website: "https://skstudio.sk", categories: ["web"] },
  { name: "TS Company Slovakia", website: "https://tscompany.sk", categories: ["web"] },
  { name: "KRISTL", website: "https://kristl.sk", categories: ["web"] },
  { name: "ULIP", website: "https://ulip.sk", categories: ["web"] },
  { name: "Trias", website: "https://trias.sk", categories: ["texty"] },
  { name: "DESIGN PROFI", website: "https://designprofi.sk", categories: ["texty"] },
  { name: "A-3DOM SK", website: "https://a-3dom.sk", categories: ["texty"] },
  { name: "AK FILTER", website: "https://akfilter.sk", categories: ["texty"] },
  { name: "LUGAPROFIT", website: "https://lugaprofit.sk", categories: ["web"] },
  { name: "VEP", website: "https://vep.sk", categories: ["texty"] },
  { name: "Interiér štúdio", website: "https://interier-studio.sk", categories: ["texty"] },
  { name: "VB Distribution", website: "https://vbdistribution.sk", categories: ["texty", "eshop"] },
  { name: "GRAYMIX", website: "https://graymix.sk", categories: ["texty"] },
  { name: "LL Design", website: "https://lldesign.sk", categories: ["texty"] },
  { name: "COFFEEIN Slovensko", website: "https://coffeein.sk", categories: ["texty"] },
  { name: "KLIMA-SHOP.SK", website: "https://klima-shop.sk", categories: ["texty", "eshop"] },
  { name: "MAQUITA", website: "https://maquita.sk", categories: ["texty"] },
  { name: "MI holding", website: "https://miholding.sk", categories: ["texty"] },
  { name: "IVAKE", website: "https://ivake.sk", categories: ["texty"] },
  { name: "SonSat", website: "https://sonsat.sk", categories: ["seo"] },
  { name: "Effectix.com", website: "https://effectix.com", categories: ["texty"] },
  { name: "KPN REAL SK", website: "https://kpnreal.sk", categories: ["web"] },
  { name: "Fiber Mounts", website: "https://fibermounts.sk", categories: ["texty"] },
  { name: "AUTODIELYBB", website: "https://autodielybb.sk", categories: ["texty"] },
  { name: "CLIMAT", website: "https://climat.sk", categories: ["web"] },
  { name: "EU-Netz", website: "https://eu-netz.sk", categories: ["social", "texty"] },
  { name: "sirux", website: "https://sirux.sk", categories: ["texty"] },
  { name: "Lovely Work", website: "https://lovelyfood.sk", categories: ["seo"] },
  { name: "CAMELUS", website: "https://camelus.sk", categories: ["cold-email"] },
  { name: "GOLF CENTRUM", website: "https://golfcentrum.sk", categories: ["texty"] },
  { name: "GIVsport", website: "https://givsport.sk", categories: ["texty"] },
  { name: "Wilmont", website: "https://wilmont.eu", categories: ["web"] },
  { name: "Johannes Senio Service", website: "https://johannessenioservice.sk", categories: ["social"] },
  { name: "MH Koncept", website: "https://mhkoncept.sk", categories: ["texty"] },
  { name: "Akter", website: "https://akter.sk", categories: ["web"] },
  { name: "BODY COLOR", website: "https://bodycolor.sk", categories: ["texty"] },
  { name: "Marble & Granite", website: "https://marble-granite.sk", categories: ["web"] },
  { name: "BAYKO", website: "https://bayko.sk", categories: ["social"] },
  { name: "RHALOTEL", website: "https://rhalotel.sk", categories: ["texty"] },
  { name: "RiGon", website: "https://rigondz.sk", categories: ["web"] },
  { name: "VÝŤAHY ZEMPLÍN", website: "https://vytahyzemplin.sk", categories: ["web"] },
  { name: "MARVA", website: "https://marva.sk", categories: ["texty", "eshop"] },
  { name: "VARIAKOV", website: "https://variakov.sk", categories: ["web"] },
  { name: "PMF", website: "https://pmf.sk", categories: ["web"] },
  { name: "EUROBROKO", website: "https://eurobroko.sk", categories: ["web"] },
  { name: "Lekárska kozmetika Life Style", website: "https://lifestylecosmetics.sk", categories: ["social"] },
  { name: "MIKO KÁVA", website: "https://mikokava.sk", categories: ["web", "eshop"] },
  { name: "Výťahy Východ PLUS", website: "https://vytahyvychodplus.sk", categories: ["web"] },
  { name: "JANEK metal-service", website: "https://janekms.sk", categories: ["web"] },
  { name: "REKOO", website: "https://rekoo.sk", categories: ["texty"] },
  { name: "Housen", website: "https://housen.sk", categories: ["web"] },
  { name: "ZVARKON", website: "https://zvarkon.sk", categories: ["web"] },
  { name: "EPIMEX ŽILINA", website: "https://epimex.sk", categories: ["web"] },
  { name: "STREMO", website: "https://stremo.sk", categories: ["web"] },
  { name: "Peter Kocian INEX-WOOD", website: "https://inexwood.sk", categories: ["web"] },
  { name: "AquaProTech", website: "https://bazenypezinok.sk", categories: ["web"] },
  { name: "SIKOSERVIS", website: "https://sikoservis.sk", categories: ["web"] },
  { name: "Mountainbiking", website: "https://mountainbiking.sk", categories: ["web"] },
  { name: "QUINTA ESSENTIA", website: "https://eventonline.sk", categories: ["seo", "texty"] },
  { name: "MHK", website: "https://mhk.sk", categories: ["cold-email"] },
  { name: "PROSPECT", website: "https://liveco.com", categories: ["eshop"] },
  { name: "Door Slovakia", website: "https://doorslovakia.sk", categories: ["web"] },
  { name: "FLOWii", website: "https://flowii.sk", categories: ["seo"] },
  { name: "ZELEŇ SLOVAKIA", website: "https://zeneslovakia.sk", categories: ["web"] },
  { name: "My GGO", website: "https://myggo.sk", categories: ["web"] },
  { name: "Etraktor", website: "https://etraktor.sk", categories: ["web"] },
  { name: "DECOR FACTORY", website: "https://svetelnyretez.cz", categories: ["web"] },
  { name: "Boggi's", website: "https://boggis.sk", categories: ["cold-email"] },
  { name: "RABA", website: "https://raba.sk", categories: ["cold-email"] },
  { name: "Ecoder", website: "https://ecoder.sk", categories: ["cold-email"] },
  { name: "IZOTREND", website: "https://izotrend.sk", categories: ["eshop"] },
  { name: "SEMI", website: "https://semi.sk", categories: ["web"] },
  { name: "Stavservis IŠTOK", website: "https://istok.sk", categories: ["web"] },
  { name: "LM Lift Stav", website: "https://lmliftstav.sk", categories: ["web"] },
  { name: "DALICE", website: "https://dalice.sk", categories: ["email-marketing"] },
  { name: "Antonio", website: "https://antonio.sk", categories: ["cold-email"] },
  { name: "Jozef Molčány MONY", website: "https://mony.sk", categories: ["cold-email"] },
];

export const categoryLabels: Record<ServiceCategory, string> = {
  'web': 'Tvorba webov',
  'eshop': 'E-shopy',
  'seo': 'SEO',
  'texty': 'SEO texty & články',
  'social': 'Sociálne médiá',
  'cold-email': 'Cold Email',
  'email-marketing': 'Email Marketing',
};
